### GET all
GET http://localhost:3000/admins

### GET one
GET http://localhost:3000/admins/1

###

### CREATE new admin
POST http://localhost:3000/admins
Content-Type: application/json

{
  "name": "Alice Smith",
  "email": "alice.smith@example.com",
  "password": "securepassword",
  "roles": ["manager", "editor"]
}

### 

### UPDATE one
PUT http://localhost:3000/admins/2
Content-Type: application/json

{

}

### 

### DELETE one
DELETE http://localhost:3000/admins/1


