@jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhbGljZS5zbWl0aEBleGFtcGxlLmNvbSIsInJvbGVzIjpbIm1hbmFnZXIiLCJlZGl0b3IiLCJhZG1pbiJdLCJpYXQiOjE3NTcyMDczMDYsImV4cCI6MTc1NzIxODEwNn0.9-2J27zhnD4Vwq3iRnPKAqzU23XWa9KKmfAMWws0wEw

### Private GET all
GET http://localhost:3000/private/products
Authorization: Bearer {{jwt}}

### GET one
GET http://localhost:3000/private/products/7
Authorization: Bearer {{jwt}}

###

### CREATE new product
POST http://localhost:3000/private/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhbGljZS5zbWl0aEBleGFtcGxlLmNvbSIsInJvbGVzIjpbIm1hbmFnZXIiLCJlZGl0b3IiLCJhZG1pbiJdLCJpYXQiOjE3NTcxNjg5MDgsImV4cCI6MTc1NzE3MjUwOH0.s_VktSuiY9WzF3r88HEOx_OgmY4uCG--vevt21_t3oc

{
  "name": "Swimming Float",
  "description": "Rubber ducky swimming float for kids.",
  "price": 12.50,
  "stock_quantity": 23
}

### CREATE new product
POST http://localhost:3000/private/products
Content-Type: application/json

{
  "name": "Jigsaw Puzzle",
  "description": "A fun and challenging 50-piece puzzle.",
  "price": 22.99,
  "stock_quantity": 50
}

### 

### UPDATE one
PATCH http://localhost:3000/private/products/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhbGljZS5zbWl0aEBleGFtcGxlLmNvbSIsInJvbGVzIjpbIm1hbmFnZXIiLCJlZGl0b3IiLCJhZG1pbiJdLCJpYXQiOjE3NTcxNzY3NzQsImV4cCI6MTc1NzE4MDM3NH0.0CJVaC4cTsrIk8j2w52i2Ny8KFeVZ0lu0SzYlUtsV0A

{
  "price": 18.99,
  "stock_quantity": 45,
  "description": "(Revised) A fun and challenging 50-piece puzzle.",
  "enabled": false
}

### 

### DELETE one
DELETE http://localhost:3000/private/products/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhbGljZS5zbWl0aEBleGFtcGxlLmNvbSIsInJvbGVzIjpbIm1hbmFnZXIiLCJlZGl0b3IiLCJhZG1pbiJdLCJpYXQiOjE3NTcwOTAzNjAsImV4cCI6MTc1NzA5Mzk2MH0.38RW_vdpzaIny5X5cy4wbW4xDBJxIG2I19etwtO_wYU



###
GET http://localhost:3000/public/products

###
GET http://localhost:3000/public/products/6
